<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\omelea-plus\mace\src\Mace.Core\Mace.Core.csproj" />
    <ProjectReference Include="..\omelea-plus\mace\src\Mace.AbstractMachines.Cam\Mace.AbstractMachines.Cam.fsproj" />
    <ProjectReference Include="..\omelea-plus\race2\src\Mephi.Cybernetics.Race.Core\Mephi.Cybernetics.Race.Core.csproj" />
  </ItemGroup>

</Project>
